api_url: http://localhost:8000
base_path: /
branch_name: master
changelog_url: https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md
host: 127.0.0.1
port: 8001
repo_url: https://github.com/openfisca/legislation-explorer.git
ui_strings: |
  {
    "en":
      { "countryName": "France", "search_placeholder": "smic, salaire net" },
    "fr":
      { "countryName": "France", "search_placeholder": "smic, salaire net" }
  }
systemd_service_file: /etc/systemd/system/legislation-explorer.service
unix_group_name: openfisca
unix_user_name: legislation-explorer

# Nginx

host_name: localhost

# Optional: SSL certificate
# An SSL certificate is issued from Let's Encrypt if `enable_ssl` and `letsencrypt_email` are both defined.
enable_ssl: no
letsencrypt_email: null
# Start by testing with staging environment, then switch to production once it works, to avoid reaching Let's Encrypt limits.
letsencrypt_environment: "staging"

# Optional: Matomo tracker

matomo_url: null
matomo_site_id: null
