aahQuery = "aah"
aahResultName = "aah"
aahResultDescription = /Allocation adulte handicapé/
aahDefinitionPeriod = /mois/
impotRevenuBaremeQuery = "impot_revenu.bareme"
impotRevenuBaremeResultDescription = "Tranches de l'IR"
smicQuery = "smic_h_b"
smicResultDescription = /SMIC horaire brut/
bouclierFiscalQuery = "bouclier_fiscal.taux"
bouclierFiscalDescription = "Taux d'imposition maximal"
