variableQuery = "disposable"
variableResultName = "disposable_income"
variableResultDescription = /Actual amount available/
variableDefinitionPeriod = /month/
scaleQuery = "taxes.social_security_contribution"
scaleResultDescription = "Social security contribution tax scale"
parameterQuery = "income tax rate"
parameterResultTitle = "taxes.income_tax_rate"
parameterResultDescription = /Income tax rate/
stoppedParameterQuery = "benefits.housing_allowance"
stoppedParameterDescription = /Housing allowance amount/
twoWordsVariableQuery = "basic income"
twoWordsVariableResultName = "basic_income"
enumVariableQuery = "housing status"
