title: "section h1",
description: ".description",
definitionPeriod: ".description + div p:nth-of-type(2)",
goBackLink: ".btn-default",
goToDependencyLink: "code a",
defaultValue:".description + div samp",
enumFirstPossibleValue: "samp",
enumFirstPossibleValueDefinition: "td:last-child",
