- name: Install Ubuntu packages
  block:
    - name: Update the cache of Ubuntu packages
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - apt-update-cache

    - name: Install Ubuntu packages
      ansible.builtin.apt:
        install_recommends: no
        name:
          - acl # Provides "setfacl" command, used by Ansible to become another Unix user
          - git
          - nodejs=10.19.0~dfsg-3ubuntu1
          - npm=6.14.4+ds-1ubuntu2
        state: present
        update_cache: no

- name: Create the Unix group for Legislation Explorer
  ansible.builtin.group:
    name: "{{ unix_group_name }}"
    state: present

- name: Create the Unix user for Legislation Explorer
  ansible.builtin.user:
    name: "{{ unix_user_name }}"
    group: "{{ unix_group_name }}"
    shell: /bin/bash
  register: unix_user

- name: Define the path of the source directory
  ansible.builtin.set_fact:
    source_dir_path: "{{ unix_user.home }}/{{ source_dir }}"

- name: Clone the Git repository of Legislation Explorer
  ansible.builtin.git:
    # Discard any local changes otherwise the task will fail.
    # Sometimes the package-lock.json is modified due to changes in its structure.
    force: yes
    repo: "{{ repo_url }}"
    dest: "{{ source_dir_path }}"
    version: "{{ branch }}"
  become_user: "{{ unix_user_name }}"

- name: Install npm dependencies
  ansible.builtin.npm:
    path: "{{ source_dir_path }}"
    production: yes
    state: present

- name: Copy the environment file for Legislation Explorer
  ansible.builtin.template:
    src: legislation-explorer.env.j2
    dest: "{{ source_dir_path }}/.env"

- name: Build the application
  ansible.builtin.command: npm run build
  args:
    chdir: "{{ source_dir_path }}"

- name: Set up the systemd service
  block:
    - name: Copy the systemd service file
      ansible.builtin.template:
        src: legislation-explorer.service.j2
        dest: "/etc/systemd/system/{{ systemd_service_file_name }}"

    - name: Enable and start the systemd service
      ansible.builtin.systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: "{{ systemd_service_file_name }}"

- name: Check that Legislation Explorer is actually started
  ansible.builtin.uri:
    return_content: yes
    status_code: 200
    timeout: 120
    url: "http://localhost:{{ app_port }}"
  register: this
  until: this.status == 200
  retries: 5 # times
  delay: 5 # Every 5 seconds
