all:
  hosts:
    vps-60ea1664.openfisca.org:
      ansible_user: root

      host_name: fr.openfisca.org
      base_path: /legislation

      api_url: https://api.fr.openfisca.org/api/latest
      port: 8100
