all:
  hosts:
    vps-60ea1664.openfisca.org:
      ansible_user: root

      api_url: https://api.fr.openfisca.org/latest
      app_port: 8100

      ui_strings: |
        {
          "en":
            { "countryName": "France", "search_placeholder": "smic, salaire net" },
          "fr":
            { "countryName": "France", "search_placeholder": "smic, salaire net" }
        }

      matomo_url: https://stats.data.gouv.fr/piwik.php
      matomo_site_id: 4

      source_dir: legislation-explorer-fr # relative to the home directory
      systemd_service_file_name: legislation-explorer-fr.service

      # Reverse proxy

      reverse_proxy_host_name: legislation.fr.openfisca.org

      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: production
