all:
  hosts:
    vps-60ea1664.openfisca.org:
      ansible_user: root

      host_name: legislation.fr.openfisca.org
      app_port: 8100

      api_url: https://api.fr.openfisca.org/latest
      country_code: fr
      ui_strings: |
        {
          "en":
            { "countryName": "France", "search_placeholder": "smic, salaire net" },
          "fr":
            { "countryName": "France", "search_placeholder": "smic, salaire net" }
        }

      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: production

      matomo_url: https://stats.data.gouv.fr/piwik.php
      matomo_site_id: 4
