all:
  hosts:
    vps-60ea1664.openfisca.org:
      ansible_user: root

      host_name: legislation.fr.openfisca.org
      port: 8100

      api_url: https://api.fr.openfisca.org/latest

      letsencrypt_email: contact@openfisca.org
      letsencrypt_environment: production

      matomo_url: https://stats.data.gouv.fr/piwik.php
      matomo_site_id: 4
