api_url = ENV["API_URL"] || "https://api.demo.openfisca.org/latest"
guest_port = 8001
host_port = ENV["PORT"] || 8001


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Used to refer to this VM from Ansible playbooks.
  config.vm.define "legislation_explorer"

  config.vm.network "forwarded_port", guest: guest_port, host: host_port

  config.vm.provider :virtualbox do |v|
    # Building Legislation Explorer takes more than the default 1024MB of memory.
    v.memory = 2048
  end

  # Provider for Docker, necessary for M1 chips
  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:ubuntu"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]
  end

  config.vm.provision :ansible, run: "always" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible/site.yml"

    ansible.host_vars = {
      "legislation_explorer" => {
        "api_url" => api_url,
        "app_host" => "0.0.0.0",
        "app_port" => guest_port,
      }
    }
  end
end
